In [2]:
import pandas as pd

data = pd.read_excel('merge_result.xlsx')
data = data.drop([data.columns[0]], axis=1)
data

,lecture_code_x,classification,classification1,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,...,grade,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive
0,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.00,강의 트는거 까먹지만 않으면 뭐 괜찮음 난 몇번 까먹었다,강의 트는 거 까먹지만 않으면 뭐 괜찮음 난 몇 번 까먹었다,"[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...","[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...",0,0.550733,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
1,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.00,학점 챙기세요 강의 트는거만 안까먹으면 됨,학점 챙기세요 강의 트는 거만 안 까먹으면 됨,"[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...","[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...",2,0.450612,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
2,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.00,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을꺼 같아요,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을 거 같아요,"[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...","[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...",2,0.452153,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
3,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.00,강의 틀기음소거유튜브 키기노래감상롤 키기솔랭진정한 광운인이 되어보자,강의 틀기 음소거 유튜브 키기 노래 감상 롤 키기 솔래 진정한 광운인 이 되어보자,"[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...","[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...",1,0.877063,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
4,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.00,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른수업 과제해도 되요,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른 수업 과제해도 돼요,"[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...","[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...",1,0.877904,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42862,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42863,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42864,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42865,0000-3-3959-01,전선,전,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,...,1.0,직접호명,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN
42866,0000-3-3959-01,전선,전,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,...,1.0,직접호명,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN

In [3]:
jeon = data[data['classification1']=='전']
jeon

,lecture_code_x,classification,classification1,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,...,grade,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive
13509,0000-2-3430-01,전선,전,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,...,1.0,직접호명,0.50,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...
13510,0000-2-3430-01,전선,전,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,...,1.0,직접호명,0.50,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...
13511,0000-2-3430-01,전선,전,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,...,1.0,직접호명,0.50,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...
13512,0000-2-3430-01,전선,전,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,...,1.0,직접호명,0.50,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...
13513,0000-2-3430-01,전선,전,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,...,1.0,직접호명,0.50,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42862,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42863,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42864,5100-4-9715-01,전선,전,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,...,1.0,직접호명,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...
42865,0000-3-3959-01,전선,전,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,...,1.0,직접호명,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN
42866,0000-3-3959-01,전선,전,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,...,1.0,직접호명,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN

In [4]:
gyeo = data[data['classification1']!='전']
gyeo

,lecture_code_x,classification,classification1,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,...,grade,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive
0,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.0,강의 트는거 까먹지만 않으면 뭐 괜찮음 난 몇번 까먹었다,강의 트는 거 까먹지만 않으면 뭐 괜찮음 난 몇 번 까먹었다,"[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...","[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...",0,0.550733,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
1,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.0,학점 챙기세요 강의 트는거만 안까먹으면 됨,학점 챙기세요 강의 트는 거만 안 까먹으면 됨,"[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...","[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...",2,0.450612,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
2,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.0,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을꺼 같아요,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을 거 같아요,"[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...","[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...",2,0.452153,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
3,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.0,강의 틀기음소거유튜브 키기노래감상롤 키기솔랭진정한 광운인이 되어보자,강의 틀기 음소거 유튜브 키기 노래 감상 롤 키기 솔래 진정한 광운인 이 되어보자,"[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...","[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...",1,0.877063,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
4,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,1.0,전자출결,0.0,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른수업 과제해도 되요,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른 수업 과제해도 돼요,"[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...","[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...",1,0.877904,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41766,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 2학기,0.0,...,0.5,직접호명,0.5,시험 매우 쉽다 수업때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 교...,시험 매우 쉽다 수업 때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 ...,"[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...","[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...",2,0.460039,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...
41767,5080-1-0109-02,기선,기,경영통계,이석준,3,4,3.81,15년 1학기,0.0,...,0.5,직접호명,0.5,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('진짜', 'Noun'), ('재밌으시고', 'Ad...",1,0.892782,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...
41768,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 1학기,0.0,...,0.5,직접호명,0.5,좋아요 학점따기 쉬움추천 하는 강의셈,좋아요 학점 따기 쉬움 추천하는 강의 셈,"[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...","[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...",1,0.891014,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...
41769,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 1학기,0.0,...,0.5,직접호명,0.5,시험문제도 쉽게 주시내요 꿀강의 교재문제 그대로 낼때도 있는데 쉬운문제만 내주심 수...,시험문제도 쉽게 주시네요 꿀 강의 교재 문제 그대로 낼 때도 있는데 쉬운 문제만 내...,"[('시험', 'Noun'), ('문제', 'Noun'), ('도', 'Josa')...","[('시험', 'Noun'), ('문제', 'Noun'), ('쉽게', 'Verb'...",1,0.878576,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...
41770,5080-1-0109-02,기선,기,경영통계,이석준,3,4,3.81,15년 1학기,0.0,...,0.5,직접호명,0.5,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는것 같네...,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는 것 같...,"[('전체', 'Noun'), ('적', 'Suffix'), ('으로', 'Josa...","[('전체', 'Noun'), ('통', 'Noun'), ('계란', 'Noun')...",1,0.893075,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...

In [33]:
jeon_info = pd.read_excel('학과.xlsx', header=None)
jeon_info

        0             1
0    H000  소프트웨어융합대학 공통
1    H020      컴퓨터정보공학부
2    H030       소프트웨어학부
3    H040        정보융합학부
4    7000   전자정보광과대학 공통
5    7060         전자공학과
6    7070       전자통신공학과
7    7420       전자융합공학과
8    7320         전기공학과
9    7340       전자재료공학과
10   7410          로봇학부
11   1000       공과대학 공통
12   1140         화학공학과
13   1160         환경공학과
14   1170         건축공학과
15   1270          건축학과
16   6000     자연과학대학 공통
17   6030          수학과
18   6050           화학과
19   6100     전자바이오물리학과
20   6130      스포츠융합과학과
21   6120       정보콘텐츠학과
22   3000   인문사회과학대학 공통
23   3040        국어국문학과
24   3220        영어산업학과
25   3110        산업심리학과
26   3230   미디어커뮤니케이션학부
27   3210     동북아문화산업학부
28  F000      정책법학대학 공통
29  F020           행정학과
30  F030            법학부
31  F050         자산관리학과
32  F040           국제학부
33   5000       경영대학 공통
34   5080          경영학부
35   5100        국제통상학부

In [34]:
jeon_info.columns = ['classification1', 'classification2']
jeon_info

   classification1 classification2
0             H000    소프트웨어융합대학 공통
1             H020        컴퓨터정보공학부
2             H030         소프트웨어학부
3             H040          정보융합학부
4             7000     전자정보광과대학 공통
5             7060           전자공학과
6             7070         전자통신공학과
7             7420         전자융합공학과
8             7320           전기공학과
9             7340         전자재료공학과
10            7410            로봇학부
11            1000         공과대학 공통
12            1140           화학공학과
13            1160           환경공학과
14            1170           건축공학과
15            1270            건축학과
16            6000       자연과학대학 공통
17            6030            수학과
18            6050             화학과
19            6100       전자바이오물리학과
20            6130        스포츠융합과학과
21            6120         정보콘텐츠학과
22            3000     인문사회과학대학 공통
23            3040          국어국문학과
24            3220          영어산업학과
25            3110          산업심리학과
26            3230     미디어커뮤니케이션학부
27            3210       동북아문화산업학부
28           F000        정책법학대학 공통
29           F020             행정학과
30           F030              법학부
31           F050           자산관리학과
32           F040             국제학부
33            5000         경영대학 공통
34            5080            경영학부
35            5100          국제통상학부

In [35]:
jeon_info['classification1'] = jeon_info['classification1'].astype(str)
jeon_info

   classification1 classification2
0             H000    소프트웨어융합대학 공통
1             H020        컴퓨터정보공학부
2             H030         소프트웨어학부
3             H040          정보융합학부
4             7000     전자정보광과대학 공통
5             7060           전자공학과
6             7070         전자통신공학과
7             7420         전자융합공학과
8             7320           전기공학과
9             7340         전자재료공학과
10            7410            로봇학부
11            1000         공과대학 공통
12            1140           화학공학과
13            1160           환경공학과
14            1170           건축공학과
15            1270            건축학과
16            6000       자연과학대학 공통
17            6030            수학과
18            6050             화학과
19            6100       전자바이오물리학과
20            6130        스포츠융합과학과
21            6120         정보콘텐츠학과
22            3000     인문사회과학대학 공통
23            3040          국어국문학과
24            3220          영어산업학과
25            3110          산업심리학과
26            3230     미디어커뮤니케이션학부
27            3210       동북아문화산업학부
28           F000        정책법학대학 공통
29           F020             행정학과
30           F030              법학부
31           F050           자산관리학과
32           F040             국제학부
33            5000         경영대학 공통
34            5080            경영학부
35            5100          국제통상학부

In [20]:
jeon['classification1'] = ''

for i in jeon.index : 
    jeon['classification1'][i] = jeon['lecture_code_x'][i][:4]
    
jeon

C:\Users\jessy\AppData\Local\Temp/ipykernel_19016/1333192777.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeon['classification1'][i] = jeon['lecture_code_x'][i][:4]

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification1
13509,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13510,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13511,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13512,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13513,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,0.5,...,직접호명,0.50,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42862,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42863,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42864,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42865,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN,0000
42866,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN,0000

In [39]:
jeon['classification1'] = jeon['classification1'].astype(str)
jeon

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification1
13509,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13510,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13511,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13512,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
13513,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,0.5,...,직접호명,0.50,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42862,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42863,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42864,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100
42865,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN,0000
42866,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN,0000

In [40]:
result_jeon = pd.merge(left=jeon, right=jeon_info, how='left', on='classification1', sort=False)
result_jeon

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification1,classification2
0,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,0.50,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000,NaN
1,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,0.5,...,0.50,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000,NaN
2,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,0.50,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000,NaN
3,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,0.5,...,0.50,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000,NaN
4,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,0.5,...,0.50,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17281,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100,국제통상학부
17282,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100,국제통상학부
17283,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,5100,국제통상학부
17284,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN,0000,NaN
17285,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN,0000,NaN

In [41]:
result_jeon.to_excel('전공.xlsx')

In [54]:
gyeo_info = pd.read_excel('교양_정보.xlsx', header=None)
# gyeo_info = gyeo_info.drop(['Unnamed: 0'], axis=1)
gyeo_info

             0                     1
0        광운인되기   필수 교양 교과목(광운인되기,영어)
1         대학영어   필수 교양 교과목(광운인되기,영어)
2    융합적사고와글쓰기  필수 교양 교과목(융합적사고와글쓰기)
3       C프로그래밍       필수 교양 교과목(정보영역)
4      프로그래밍기초       필수 교양 교과목(정보영역)
..         ...                   ...
218       교육실습                교직 교과목
219       교직실무                교직 교과목
220     교육봉사활동                교직 교과목
221        안보학               군사학 교과목
222      조직리더십               군사학 교과목

[223 rows x 2 columns]

In [55]:
gyeo_info.columns = ['lecture_name', 'classification2']
gyeo_info

    lecture_name       classification2
0          광운인되기   필수 교양 교과목(광운인되기,영어)
1           대학영어   필수 교양 교과목(광운인되기,영어)
2      융합적사고와글쓰기  필수 교양 교과목(융합적사고와글쓰기)
3         C프로그래밍       필수 교양 교과목(정보영역)
4        프로그래밍기초       필수 교양 교과목(정보영역)
..           ...                   ...
218         교육실습                교직 교과목
219         교직실무                교직 교과목
220       교육봉사활동                교직 교과목
221          안보학               군사학 교과목
222        조직리더십               군사학 교과목

[223 rows x 2 columns]

In [56]:
result_gyeo = pd.merge(left=gyeo, right=gyeo_info, how='left', on='lecture_name', sort=False)
result_gyeo

,lecture_code_x,classification,classification1,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification2
0,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,전자출결,0.0,강의 트는거 까먹지만 않으면 뭐 괜찮음 난 몇번 까먹었다,강의 트는 거 까먹지만 않으면 뭐 괜찮음 난 몇 번 까먹었다,"[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...","[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...",0,0.550733,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
1,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,전자출결,0.0,학점 챙기세요 강의 트는거만 안까먹으면 됨,학점 챙기세요 강의 트는 거만 안 까먹으면 됨,"[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...","[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...",2,0.450612,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
2,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,전자출결,0.0,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을꺼 같아요,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을 거 같아요,"[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...","[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...",2,0.452153,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
3,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,전자출결,0.0,강의 틀기음소거유튜브 키기노래감상롤 키기솔랭진정한 광운인이 되어보자,강의 틀기 음소거 유튜브 키기 노래 감상 롤 키기 솔래 진정한 광운인 이 되어보자,"[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...","[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...",1,0.877063,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
4,0000-1-8128-01,교필,교,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,...,전자출결,0.0,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른수업 과제해도 되요,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른 수업 과제해도 돼요,"[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...","[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...",1,0.877904,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25576,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 2학기,0.0,...,직접호명,0.5,시험 매우 쉽다 수업때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 교...,시험 매우 쉽다 수업 때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 ...,"[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...","[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...",2,0.460039,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25577,5080-1-0109-02,기선,기,경영통계,이석준,3,4,3.81,15년 1학기,0.0,...,직접호명,0.5,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('진짜', 'Noun'), ('재밌으시고', 'Ad...",1,0.892782,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25578,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 1학기,0.0,...,직접호명,0.5,좋아요 학점따기 쉬움추천 하는 강의셈,좋아요 학점 따기 쉬움 추천하는 강의 셈,"[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...","[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...",1,0.891014,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25579,5080-1-0109-02,기선,기,경영통계,이석준,3,5,3.81,15년 1학기,0.0,...,직접호명,0.5,시험문제도 쉽게 주시내요 꿀강의 교재문제 그대로 낼때도 있는데 쉬운문제만 내주심 수...,시험문제도 쉽게 주시네요 꿀 강의 교재 문제 그대로 낼 때도 있는데 쉬운 문제만 내...,"[('시험', 'Noun'), ('문제', 'Noun'), ('도', 'Josa')...","[('시험', 'Noun'), ('문제', 'Noun'), ('쉽게', 'Verb'...",1,0.878576,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25580,5080-1-0109-02,기선,기,경영통계,이석준,3,4,3.81,15년 1학기,0.0,...,직접호명,0.5,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는것 같네...,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는 것 같...,"[('전체', 'Noun'), ('적', 'Suffix'), ('으로', 'Josa...","[('전체', 'Noun'), ('통', 'Noun'), ('계란', 'Noun')...",1,0.893075,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN

In [57]:
result_gyeo.to_excel('교양.xlsx')

In [58]:
result_jeon = pd.read_excel('전공.xlsx')
result_jeon = result_jeon.drop(['Unnamed: 0'], axis=1)
result_jeon

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification2
0,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
1,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
2,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
3,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,0.5,...,직접호명,0.50,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
4,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,0.5,...,직접호명,0.50,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17281,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,통상학과라면 꼭 들어보는거 추천드려요 기말고사가 없어서 기말때 다른 공부할 시간이 ...,통상학과라면 꼭 들어보는 거 추천드려요 기말고사가 없어서 기말 때 다른 공부 할 시...,"[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...","[('통상', 'Noun'), ('학과', 'Noun'), ('라면', 'Noun'...",1,0.888680,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,국제통상학부
17282,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,교수님이 정말 좋으시고 학생들에게 진심어린 애정이 느껴지십니다,교수님이 정말 좋으시고 학생들에게 진심 어린 애정이 느껴지십니다,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('좋으시고', 'Adj...",1,0.894557,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,국제통상학부
17283,5100-4-9715-01,전선,통상과환경,임종수,3,5,5.00,19년 2학기,0.5,0.5,...,직접호명,0.25,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,절편이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,"[('절편', 'Noun'), ('이', 'Suffix'), ('면', 'Josa'...","[('절편', 'Noun'), ('학점', 'Noun'), ('보장', 'Noun'...",1,0.890130,절평이면 학점 보장 배워가는 것도 많고 무엇보다 수업에 애정이 있는 게 보일 정도로...,국제통상학부
17284,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,현행 교육과정에 대한 전반적인 이해와 이를 기반으로한 수업 설계가 주된 수업 내용입니다,현행 교육과정에 대한 전반적인 이해와 이를 기반으로 한 수업 설계가 주된 수업 내용입니다,"[('현행', 'Noun'), ('교육과정', 'Noun'), ('에', 'Josa...","[('현행', 'Noun'), ('교육과정', 'Noun'), ('대한', 'Nou...",1,0.470754,NaN,NaN
17285,0000-3-3959-01,전선,교과교육론(상업),NaN,0,5,0.00,21년 2학기,0.5,0.5,...,직접호명,0.25,교과교재연구및지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져주시는...,교과 교재연구 및 지도법은 모의수업이 있었던 반면 위 수업은 수업 중 교수님이 던져...,"[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...","[('교과', 'Noun'), ('교재', 'Noun'), ('연구', 'Noun'...",1,0.829567,NaN,NaN

In [61]:
result_gyeo = pd.read_excel('교양.xlsx')
result_gyeo = result_gyeo.drop(['Unnamed: 0'], axis=1)
result_gyeo

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification2
0,0000-1-8128-01,교필,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,0.5,...,전자출결,0.0,강의 트는거 까먹지만 않으면 뭐 괜찮음 난 몇번 까먹었다,강의 트는 거 까먹지만 않으면 뭐 괜찮음 난 몇 번 까먹었다,"[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...","[('강의', 'Noun'), ('트는', 'Verb'), ('거', 'Noun')...",0,0.550733,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
1,0000-1-8128-01,교필,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,0.5,...,전자출결,0.0,학점 챙기세요 강의 트는거만 안까먹으면 됨,학점 챙기세요 강의 트는 거만 안 까먹으면 됨,"[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...","[('학점', 'Noun'), ('챙기세요', 'Verb'), ('강의', 'Nou...",2,0.450612,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
2,0000-1-8128-01,교필,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,0.5,...,전자출결,0.0,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을꺼 같아요,매우 맛있는 과목 그냥 너무 맛있어서 이가 썩을 거 같아요,"[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...","[('매우', 'Noun'), ('맛있는', 'Adjective'), ('과목', ...",2,0.452153,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
3,0000-1-8128-01,교필,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,0.5,...,전자출결,0.0,강의 틀기음소거유튜브 키기노래감상롤 키기솔랭진정한 광운인이 되어보자,강의 틀기 음소거 유튜브 키기 노래 감상 롤 키기 솔래 진정한 광운인 이 되어보자,"[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...","[('강의', 'Noun'), ('틀기', 'Verb'), ('음소거', 'Noun...",1,0.877063,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
4,0000-1-8128-01,교필,광운인되기,김정권,1,5,4.88,22년 1학기,0.0,0.5,...,전자출결,0.0,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른수업 과제해도 되요,그냥 쉽게 학점 가져가는 과목 강의 틀어두고 다른 수업 과제해도 돼요,"[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...","[('그냥', 'Noun'), ('쉽게', 'Verb'), ('학점', 'Noun'...",1,0.877904,과제 중간에 한번씩 있는데 레포트 이런 거 아니니까 편하게 하시면 됩니다. 추가된거...,"필수 교양 교과목(광운인되기,영어)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25576,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 2학기,0.0,0.5,...,직접호명,0.5,시험 매우 쉽다 수업때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 교...,시험 매우 쉽다 수업 때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 ...,"[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...","[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...",2,0.460039,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25577,5080-1-0109-02,기선,경영통계,이석준,3,4,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('진짜', 'Noun'), ('재밌으시고', 'Ad...",1,0.892782,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25578,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,좋아요 학점따기 쉬움추천 하는 강의셈,좋아요 학점 따기 쉬움 추천하는 강의 셈,"[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...","[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...",1,0.891014,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25579,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,시험문제도 쉽게 주시내요 꿀강의 교재문제 그대로 낼때도 있는데 쉬운문제만 내주심 수...,시험문제도 쉽게 주시네요 꿀 강의 교재 문제 그대로 낼 때도 있는데 쉬운 문제만 내...,"[('시험', 'Noun'), ('문제', 'Noun'), ('도', 'Josa')...","[('시험', 'Noun'), ('문제', 'Noun'), ('쉽게', 'Verb'...",1,0.878576,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25580,5080-1-0109-02,기선,경영통계,이석준,3,4,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는것 같네...,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는 것 같...,"[('전체', 'Noun'), ('적', 'Suffix'), ('으로', 'Josa...","[('전체', 'Noun'), ('통', 'Noun'), ('계란', 'Noun')...",1,0.893075,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN

In [62]:
result = pd.concat([result_jeon,result_gyeo])
result

,lecture_code_x,classification,lecture_name,professor_name,credit,score,avg_score,semester,group_meeting,assignment,...,attendance,test_n,lecture_review,revised_review,word,token,model_pre,pred,extractive,classification2
0,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.5,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,힐링이긴 하나 시험으로 점수가 많이 갈림 그런데 그 시험 준비가 정말 빡셈,"[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...","[('힐링', 'Noun'), ('이긴', 'Verb'), ('하나', 'Noun'...",2,0.444405,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
1,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,21년 1학기,0.0,0.5,...,직접호명,0.5,과목 수강신청 하기 전에 알아두어야 할 것이 과목은 연계전공생에겐 전공 필수예 그렇...,과목 수강신청하기 전에 알아두어야 할 것이 과목은 연계 전공생에겐 전공 필수에 그렇...,"[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...","[('과목', 'Noun'), ('수강신청', 'Noun'), ('하기', 'Ver...",1,0.882986,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
2,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,4,4.63,21년 1학기,0.0,0.5,...,직접호명,0.5,교수님은 정말 말할 것도 없이 천사심 다만 수강인원이 적고 공부할 양이 많아서 학점...,교수님은 정말 말할 것도 없이 천사 심 다만 수강인원이 적고 공부할 양이 많아서 학...,"[('교수', 'Noun'), ('님', 'Suffix'), ('은', 'Josa'...","[('교수', 'Noun'), ('정말', 'Noun'), ('말', 'Noun')...",1,0.880430,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
3,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,3,4.63,21년 1학기,0.0,0.5,...,직접호명,0.5,생각보다 연계전공 하려는 능력자들이 많아서 학점 받기는 깐깐한거 같음 교수님이 정말...,생각보다 연계전공하려는 능력자들이 많아서 학점 받기는 깐깐한 거 같음 교수님이 정말...,"[('생각', 'Noun'), ('보다', 'Josa'), ('연', 'Modifi...","[('생각', 'Noun'), ('계', 'Noun'), ('전공', 'Noun')...",2,0.443855,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
4,0000-2-3430-01,전선,인간행동과사회환경,구지윤,3,5,4.63,20년 1학기,0.0,0.5,...,직접호명,0.5,갓지윤비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정을 ...,갓 지윤 비대면이라 아쉬웠지만 과제를 통해서 나를 돌아보게 되었고 수업도 항상 열정...,"[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...","[('갓', 'Noun'), ('지윤', 'Noun'), ('비', 'Noun'),...",1,0.896429,전 사회복지 연계전공도 아니고 타과생이 그냥 교양으로 들었는데 그냥 수업도 좋고 과...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25576,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 2학기,0.0,0.5,...,직접호명,0.5,시험 매우 쉽다 수업때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 교...,시험 매우 쉽다 수업 때 공란이 있는 파일로 수업을 하시고 강의 자료로 주시는데 ...,"[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...","[('시험', 'Noun'), ('매우', 'Noun'), ('쉽다', 'Verb'...",2,0.460039,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25577,5080-1-0109-02,기선,경영통계,이석준,3,4,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,교수님이 진짜 재밌으시고 잘 가르쳐주심 중고등학교 때 배운 것들 중심이어서 어렵지는...,"[('교수', 'Noun'), ('님', 'Suffix'), ('이', 'Josa'...","[('교수', 'Noun'), ('진짜', 'Noun'), ('재밌으시고', 'Ad...",1,0.892782,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25578,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,좋아요 학점따기 쉬움추천 하는 강의셈,좋아요 학점 따기 쉬움 추천하는 강의 셈,"[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...","[('좋아요', 'Adjective'), ('학점', 'Noun'), ('따기', ...",1,0.891014,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25579,5080-1-0109-02,기선,경영통계,이석준,3,5,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,시험문제도 쉽게 주시내요 꿀강의 교재문제 그대로 낼때도 있는데 쉬운문제만 내주심 수...,시험문제도 쉽게 주시네요 꿀 강의 교재 문제 그대로 낼 때도 있는데 쉬운 문제만 내...,"[('시험', 'Noun'), ('문제', 'Noun'), ('도', 'Josa')...","[('시험', 'Noun'), ('문제', 'Noun'), ('쉽게', 'Verb'...",1,0.878576,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN
25580,5080-1-0109-02,기선,경영통계,이석준,3,4,3.81,15년 1학기,0.0,0.5,...,직접호명,0.5,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는것 같네...,전체적으로 통계란 무엇인가에 대해 한번 훑는 정도의 수업이라 큰 어려움 없는 것 같...,"[('전체', 'Noun'), ('적', 'Suffix'), ('으로', 'Josa...","[('전체', 'Noun'), ('통', 'Noun'), ('계란', 'Noun')...",1,0.893075,개인적으로 좋아했던 과목인데 교수님 성격까지 좋아서 더 재미있게 공부함 그렇지만 중...,NaN

In [63]:
result.to_excel('add_classification2.xlsx')